#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Console\CalculatorCommand;

$app = new Application('RPN Calculator', 'v1.0.0');
$app -> add(new CalculatorCommand());
$app -> run();